server:
  port: 8080

spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist

  # Primary Database
  primary-datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: devchong
    password: Y2kim2A!

  # Secondary Database
  secondary-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: devchong
    password: Y2kim2A!

  # jpa properties
  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    open-in-view: false
#    generate-ddl: true
    show-sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      encoding: UTF-8
#      mode: always
#      platform: postgresql
